extends Resource
class_name ModKitRecipe

@export var id: String = ""  # unique string (include the lowercase name of the building, e.g., "smelter", for recipes meant for Smelters)
@export var display_name: String = ""  # in-game name
@export var inputs: Dictionary[int, int] = {}  # inputs for one turnover, in the form of {1:2}, which would be 2 units of the resource with Enum value of 1 (Ore)
@export var outputs: Dictionary[int, int] = {}  # outputs for one turnover, in the form of {1:2}, which would be 2 units of the resource with Enum value of 1 (Ore)
@export var production_time: float = 5.0  # how many seconds should one production cycle take
@export var energy_consumption: int = 5  # how much energy does this recipe consume extra
@export var required_building_level: int = 1  # what level does the building have to be to access this recipe
@export var required_research: String = ""  # which research ID unlocks this recipe
@export var byproducts: Dictionary[int, float] = {}  # whether there are possible byproducts for this recipe, in the form of {1: 0.2}, which would be a 20% chance of producing Ore as a byproduct
@export var mana_consumption: float = 0.0  # how much Mana per production cycle does this recipe consume extra
@export var heat_production: float = 0.0  # How much heat is produced (positive) or consumed (negative) per crafting cycle (-100 to 100) [Note: anything intended to be used pre-Act II should keep this at 0]
@export var corrosion_production: float = 0.0  # Corrosion delay added (positive) or removed (negative) per crafting cycle [pre-Act II content should keep this at 0]
@export var xp_reward: int = 1  # How much XP to award the building for each crafting cycle
@export var alternate_recipe: bool = false  # Whether recipe is considered to be alternate (e.g., coming from chests/merchants); mainly used in the online calculator

# Enum IDs for all resources:

#NONE = 0,
#ORE = 1,  # phase 1
#INGOT = 2,  # phase 1
#MAGIC_ESSENCE = 3,  # phase 1
#COMPONENT = 4,  # phase 1
#SUNDROP = 5,  # phase 1
#GOLD_ORE = 6,  # phase 1
#IRON_KEY = 7,  # phase 1
#GOLD_INGOT = 8,  # phase 1
#GOLD_KEY = 9,  # phase 1
#ARCANE_CRYSTAL = 10,  # phase 1
#ADVANCED_MACHINERY = 11,  # phase 1
#ARCANE_DEVICE = 12,  # phase 1
#MASTER_COMPONENT = 13,  # phase 1
#MANA_BOMB = 14,  # phase 1
#ARCANE_CANNON = 15,  # phase 1
#SIEGE_CRYSTAL = 16,  # phase 1
#COAL = 17,  # phase 1
#CINDER = 18,  # phase 1
#COPPER_ORE = 19,  # phase 2
#TIN_ORE = 20,  # phase 2
#STEEL_INGOT = 21,  # phase 2
#COPPER_INGOT = 22,  # phase 2
#TIN_INGOT = 23,  # phase 2
#BRONZE_INGOT = 24,  # phase 2
#LIMESTONE = 25,  # phase 2
#SILVER_ORE = 26,  # phase 2
#SILVER_INGOT = 27,  # phase 2
#MITHRIL_ORE = 28,  # phase 3
#MITHRIL_INGOT = 29,  # phase 3
#CRYSTAL_ORE = 30,  # phase 3
#CRYSTAL_INGOT = 31,  # phase 3
#ADAMANTINE_ORE = 32,  # phase 3
#ADAMANTINE_INGOT = 33,  # phase 3
#VOIDSTONE_ORE = 34,  # phase 3
#VOIDSTEEL_INGOT = 35,  # phase 3
#STARFALL_ORE = 36,  # phase 3
#STARSTEEL_INGOT = 37,  # phase 3
#ELECTRUM_INGOT = 38,  # phase 2
#MITHRIL_ALLOY = 39,  # phase 3
#ETHEREAL_STEEL = 40,  # phase 3
#SLAG = 41,  # phase 2
#FLUX = 42,  # phase 2
#METAL_DUST = 43,  # phase 3
#CRYSTAL_POWDER = 44,  # phase 3
#RUNESTONE = 45,  # phase 3
#ENCHANTED_STEEL = 46,  # phase 3
#PURE_ESSENCE = 47,  # phase 3
#GOLD_COMPONENT = 48,  # phase 1
#CRYSTALLIZED_COAL = 49,  # phase 2
#CRYSTAL_KEY = 50,  # phase 3
#WATER = 51,  # phase 2
#BRONZE_CASING = 52,  # phase 2
#DURABLE_HOUSING = 53,  # phase 2
#REINFORCED_PLATING = 54,  # phase 2
#FORTRESS_MACHINERY = 55,  # phase 2
#BLESSED_CONDUIT = 56,  # phase 2
#HARMONIC_RESONATOR = 57,  # phase 2
#SANCTIFIED_CORE = 58,  # phase 2
#PURIFIED_SOLVENT = 59,  # phase 2
#REFINED_FUEL = 60,  # phase 2
#CONCENTRATED_ENERGY = 61,  # phase 2
#BRONZE_KEY = 62,  # phase 2
#HARMONIC_KEY = 63,  # phase 2
#ARCHITECT_BANE = 64,  # phase 2
#WARD_BREAKER = 65,  # phase 2
#REALITY_REND = 66,  # phase 2
#OIL = 67,  # phase 2
#CRYSTAL_WIRE = 68,  # phase 3
#ADAMANTINE_COMPONENT = 69,  # phase 3
#DIMENSIONAL_COMPONENT = 70,  # phase 3
#HYBRID_MATRIX = 71,  # phase 3
#CRYSTAL_ASSEMBLY = 72,  # phase 3
#TITAN_ASSEMBLY = 73,  # phase 3
#DIMENSIONAL_CONVERGENCE = 74,  # phase 3
#RUNIC_PLATING = 75,  # phase 3
#REFINED_AMALGAM = 76,  # phase 3
#ESSENCE_WASH = 77,  # phase 3
#VOID_KEY = 78,  # phase 3
#VOID_SPLITTER = 79,  # phase 3
#STAR_RENDER = 80,  # phase 3
#LEGION_ANNIHILATOR = 81,  # phase 3
#COPPER_WIRE = 82,  # phase 2
#STEEL_PLATE = 83,  # phase 2
#VOID_CUBES = 84,  # phase 3
#STELLAR_FUEL = 85,  # phase 3
#STEEL_COMPONENT = 86,  # phase 2
#ULTRA_COMPONENT = 87,  # phase 2
#GEODE = 88,  # phase 2
#VOID_COMPONENT = 89,  # phase 3
#VOID_CHAMBER = 90,  # phase 3
#STELLAR_COMPONENT = 91,  # phase 3
#RESONANT_CORE = 92,  # phase 3
#STELLAR_ASSEMBLY = 93,  # phase 3
#MITHRIL_COMPONENT = 94,  # phase 3
#ENHANCED_CORE = 95,  # phase 3
#ETHEREAL_ASSEMBLY = 96,  # phase 3
#RUNIC_MATRIX = 97,  # phase 3
#STAR_CORE = 98,  # phase 3
#QUANTUM_SYSTEM = 99,  # phase 3
#CELESTIAL_SYSTEM = 100,  # phase 3
#STAR_SYSTEM = 101,  # phase 3
#CELESTIAL_MATRIX = 102,  # phase 3
#ETERNAL_ASSEMBLY = 103,  # phase 3
#COSMIC_ASSEMBLY = 104,  # phase 3
#RADIANT_ASSEMBLY = 105,  # phase 3
#LEGION_FRAME = 106,  # phase 3
#LEGION_CORE = 107,  # phase 3
#LEGION_MATRIX = 108,  # phase 3
#MOD_RESOURCE_1..10 = 1000..1009
